baseURL = "http://localhost:1313/" 
languageCode = "en-us"
theme = "hugo-book"
title = "Sandwich"

[params]
BookTheme = "light"
BookSearch = false
BookToC = true
BookComments = false
BookLogo = "/images/ckt-logo.png"

[markup.goldmark.renderer]
  unsafe = true

[markup]
  [markup.highlight]
    style = "onedark" 
    noClasses = true
